### ISSUE TITLE
Missing `controllabe-ap`?

### ISSUE THREAD

**Issue by 5nizza** [SYNTCOMP/hoa-tools#2]
The following benchmark does not have the header item `controllable-AP:`, which seems fishy, since the source benchmark does have inputs and outputs: 
https://github.com/SYNTCOMP/hoa-tools/blob/master/examples/amba_decomposed_arbiter.tlsf.ehoa

(the original benchmark is https://github.com/SYNTCOMP/benchmarks/blob/master/tlsf/amba_decomposed/amba_decomposed_arbiter.tlsf)

**Comment by gaperez64** [comment]
Interesting! I will take a look at the translation again.

**Comment by gaperez64** [comment]
I pushed and updated version of the benchmarks using the new version of spot. I think I also had a bug in [this script](https://github.com/gaperez64/tlsf2gpg/blob/master/tlsf2gpg.sh) when I generated the first version of the files. I checked and they all have a `controllable-AP` tag now. @5nizza will you merge/copy them to the benchmark repository?

**Comment by 5nizza** [comment]
Thanks for quick fix! (I discovered this by pure accident.)
Aaahhaha, no, Guillermo, I can't merge them to syntcomp since i want to handle only aiger and tlsf parts of syntcomp for now, but nice try:))))))))

**Comment by gaperez64** [comment]
It's my inner professor trying to delegate things subconsciously :D I will merge them into the benchmarks, thanks for the bug report!
