### ISSUE TITLE
Inefficiency in the parser

### ISSUE THREAD

**Issue by gaperez64** [SYNTCOMP/hoa-tools#3]
This was submitted by @trolando

He says:

You designed hoa.y to be right recursive instead of left recursive, see https://www.gnu.org/software/bison/manual/html_node/Recursion.html, the parser will simply break on large input files.

You can patch this as follows:

diff --git a/src/hoa.y b/src/hoa.y
index d97e8fa..0a2352b 100644
--- a/src/hoa.y
+++ b/src/hoa.y
@@ -197,15 +197,23 @@ static StateList* newStateNode(int id, char* name, BTree* label, IntList* accSig
     list->name = name;
     list->label = label;
     list->accSig = accSig;
+    list->next = NULL;
     list->transitions = NULL;
     return list;
 }
 
-static StateList* prependStateNode(StateList* node, StateList* newNode,
+static StateList* appendStateNode(StateList* node, StateList* newNode,
                             TransList* transitions) {
-    newNode->next = node;
     newNode->transitions = transitions;
-    return newNode;
+    if (node == NULL) {
+        return newNode; // nothing to do
+    } else {
+        // find last in list, add it
+        StateList *last = node;
+        while (last->next != NULL) last = last->next;
+        last->next = newNode;
+        return node;
+    }
 }
 
 static TransList* prependTransNode(TransList* node , BTree* label,
@@ -607,9 +615,9 @@ body: statespec_list
     ;
 
 statespec_list: /* empty */ { $$ = NULL; }
-              | state_name trans_list statespec_list
+              | statespec_list state_name trans_list
               {
-                $$ = prependStateNode($3, $1, $2);
+                $$ = appendStateNode($1, $2, $3);
               }
               ;

Notice how I changed statespec_list to be left recursive instead of right recursive, I then have to change prepend to append and fix the struct initialization.

This does not solve all the right recursions though.

**Comment by trolando** [comment]
If you want I could make a pull request or you can straight forward extract the improved version from knor source code  https://github.com/trolando/knor/tree/master/src

**Comment by gaperez64** [comment]
I will (or rather, one of my master's students will) extract it from knor's source, thanks @trolando !
